from os import getenv

BACKEND_POSTGRES_HOST = getenv("BACKEND_POSTGRES_HOST", "db")
BACKEND_POSTGRES_PORT = getenv("BACKEND_POSTGRES_PORT", "5432")
BACKEND_POSTGRES_NAME = getenv("BACKEND_POSTGRES_NAME", "todo_postgres")
BACKEND_POSTGRES_USERNAME = getenv("BACKEND_POSTGRES_USERNAME", "todo_postgres")
BACKEND_POSTGRES_PASSWORD = getenv("BACKEND_POSTGRES_PASSWORD", "todo_postgres")